# Importing all the libraries and loading the data

In [1]:
import pandas as pd
import numpy as np
import sklearn

## For Feature Selection
from sklearn.feature_selection import RFE

## For Splitting data into Test and Train sets
from sklearn.model_selection import train_test_split

## For Classfication Models
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from xgboost import XGBClassifier

## For Accuracy
import statsmodels
import statsmodels.api as sm
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
pd.set_option('max_columns', 500)
pd.set_option('max_rows', 500)
pd.set_option('max_colwidth', -1)

In [3]:
## Please update the file name as per chosen dataset.
all_Features = pd.read_csv('All_Features_No_Norm.csv', sep=',', index_col=0)

In [4]:
all_Features.shape

(10949, 186)

In [5]:
all_Features.head()

domain  \
0  nutritionfacts.org   
1  nutritionfacts.org   
2  nutritionfacts.org   
3  nutritionfacts.org   
4  nutritionfacts.org   

                                                                     url  \
0  https://nutritionfacts.org/audio/fighting-fatigue/                      
1  https://nutritionfacts.org/audio/new-thoughts-on-a-healthy-weight/      
2  https://nutritionfacts.org/audio/the-latest-on-childrens-health/        
3  https://nutritionfacts.org/audio/beans-beans-the-truth-about-lectins/   
4  https://nutritionfacts.org/audio/new-research-on-cholesterol/           

    urlType  L_WC  L_Analytic  L_Clout  L_Authentic  L_Tone  L_WPS  L_Sixltr  \
0  Reliable  1241  73.48       52.26    23.58        1.68    8.99   43.27      
1  Reliable  1262  79.00       53.80    15.76        87.14   10.34  36.29      
2  Reliable  1306  75.75       56.09    26.05        39.46   11.36  38.82      
3  Reliable  1879  76.11       52.55    16.33        29.33   10.56  36.56      
4  Reliable  1475  76.03       53.25    32.67        37.78   9.77   39.66      

   L_Dic  L_function  L_pronoun  L_ppron   L_i  L_we  L_you  L_shehe  L_they  \
0  70.91  12.33       2.01       1.13     0.32  0.24  0.32   0.0      0.24     
1  72.90  10.30       1.74       0.79     0.24  0.16  0.32   0.0      0.08     
2  73.43  11.56       1.07       0.46     0.23  0.00  0.23   0.0      0.00     
3  72.43  12.13       2.02       0.90     0.27  0.32  0.32   0.0      0.00     
4  70.31  12.07       2.51       1.29     0.27  0.54  0.41   0.0      0.07     

   L_ipron  L_article  L_prep  L_auxverb  L_adverb  L_conj  L_negate  L_verb  \
0  0.89     0.0        1.85    3.38       4.35      1.13    3.14      13.46    
1  0.95     0.0        1.51    3.09       3.33      0.48    2.54      12.60    
2  0.61     0.0        1.68    3.45       4.44      1.38    2.53      11.03    
3  1.12     0.0        1.81    3.99       3.73      0.90    2.18      14.58    
4  1.22     0.0        2.17    3.25       3.59      1.15    2.71      13.02    

   L_adj  L_compare  L_interrog  L_number  L_quant  L_affect  L_posemo  \
0  5.24   1.93       0.32        2.34      2.01     8.94      2.90       
1  7.21   3.49       0.24        3.09      4.75     7.05      5.31       
2  7.27   4.29       0.31        3.68      2.22     6.97      3.83       
3  5.80   2.34       0.32        3.67      2.61     6.87      3.46       
4  5.63   2.78       0.34        4.61      2.78     8.00      4.34       

   L_negemo  L_anx  L_anger  L_sad  L_social  L_family  L_friend  L_female  \
0  5.88      0.73   0.81     1.53   6.37      0.16      0.08      0.08       
1  1.74      0.79   0.00     0.79   5.55      0.08      0.00      0.32       
2  3.06      0.77   0.38     0.46   7.50      0.31      0.54      0.23       
3  3.25      0.64   0.90     0.48   5.22      0.05      0.05      0.21       
4  3.66      1.22   0.54     0.95   5.83      0.34      0.00      0.20       

   L_male  L_cogproc  L_insight  L_cause  L_discrep  L_tentat  L_certain  \
0  0.16    17.08      4.43       3.95     1.37       3.06      2.34        
1  0.24    14.74      3.49       4.36     0.79       2.61      2.22        
2  0.08    13.94      3.68       2.76     0.54       3.06      1.53        
3  0.11    16.60      4.26       3.19     1.65       3.25      2.45        
4  0.34    14.24      3.73       2.98     1.56       2.85      1.56        

   L_differ  L_percept  L_see  L_hear  L_feel  L_bio  L_body  L_health  \
0  2.90      6.04       2.01   0.24    2.26    15.55  1.77    10.56      
1  2.30      4.36       0.63   0.40    2.93    21.47  2.46    4.28       
2  3.29      6.97       1.53   0.61    1.23    18.38  2.91    6.97       
3  2.77      3.41       1.81   0.48    0.69    17.88  2.55    7.18       
4  2.98      3.12       1.22   0.54    0.41    15.39  2.92    9.56       

   L_sexual  L_ingest  L_drives  L_affiliation  L_achieve  L_power  L_reward  \
0  0.24      3.95      7.90      1.53           1.53       2.01     

In [6]:
all_Features.tail()

domain  \
10944  thetruthdivision.com   
10945  thetruthdivision.com   
10946  thetruthdivision.com   
10947  thetruthdivision.com   
10948  thetruthdivision.com   

                                                                                                                            url  \
10944  http://thetruthdivision.com/2016/12/shock-trump-supporter-scott-baio-attacked-for-political-beliefs-files-police-report/   
10945  http://thetruthdivision.com/2017/02/breaking-teacher-fired-shocking-statement-trump-supporters/                            
10946  http://thetruthdivision.com/2016/11/obama-tells-trump-presidency-cant-treated-casually-golfs-324-times/                    
10947  http://thetruthdivision.com/2017/03/just-trumps-golf-course-vandalized/                                                    
10948  http://thetruthdivision.com/2017/05/popular-game-show-host-requests-new-provision-added-acha-liberals-ticked/              

      urlType  L_WC  L_Analytic  L_Clout  L_Authentic  L_Tone  L_WPS  \
10944  Fake    157   90.55       79.61    5.62         37.02   10.47   
10945  Fake    124   91.63       90.14    34.13        83.22   12.40   
10946  Fake    145   80.39       55.48    13.87        37.99   16.11   
10947  Fake    151   89.60       78.67    19.75        50.49   11.62   
10948  Fake    84    89.26       96.27    9.40         95.81   9.33    

       L_Sixltr  L_Dic  L_function  L_pronoun  L_ppron  L_i  L_we  L_you  \
10944  40.76     57.96  5.73        0.00       0.00     0.0  0.00  0.00    
10945  53.23     63.71  6.45        0.81       0.00     0.0  0.00  0.00    
10946  37.93     60.00  10.34       2.07       0.69     0.0  0.69  0.00    
10947  38.41     61.59  5.96        0.00       0.00     0.0  0.00  0.00    
10948  42.86     58.33  4.76        1.19       1.19     0.0  0.00  1.19    

       L_shehe  L_they  L_ipron  L_article  L_prep  L_auxverb  L_adverb  \
10944  0.0      0.0     0.00     0.64       1.27    3.18       0.64       
10945  0.0      0.0     0.81     0.81       1.61    0.81       1.61       
10946  0.0      0.0     1.38     0.69       0.69    1.38       2.76       
10947  0.0      0.0     0.00     0.00       1.32    0.66       0.00       
10948  0.0      0.0     0.00     0.00       1.19    1.19       2.38       

       L_conj  L_negate  L_verb  L_adj  L_compare  L_interrog  L_number  \
10944  0.00    0.64      12.74   8.28   1.91       0.0         1.27       
10945  0.00    0.81      11.29   2.42   1.61       0.0         1.61       
10946  0.69    3.45      8.97    1.38   0.69       0.0         3.45       
10947  0.66    3.31      4.64    5.30   1.32       0.0         3.31       
10948  0.00    0.00      11.90   3.57   1.19       0.0         0.00       

       L_quant  L_affect  L_posemo  L_negemo  L_anx  L_anger  L_sad  L_social  \
10944  0.00     12.10     6.37      5.73      0.00   3.82     0.64   9.55       
10945  0.81     11.29     7.26      4.03      1.61   1.61     0.00   14.52      
10946  0.00     8.28      3.45      2.76      1.38   0.69     0.00   8.97       
10947  2.65     2.65      1.99      0.66      0.66   0.00     0.00   11.92      
10948  1.19     9.52      7.14      2.38      1.19   0.00     0.00   16.67      

       L_family  L_friend  L_female  L_male  L_cogproc  L_insight  L_cause  \
10944  0.64      0.00      1.91      0.0     8.28       2.55       1.27      
10945  0.00      0.00      0.00      0.0     8.06       2.42       2.42      
10946  0.69      0.00      0.00      0.0     9.66       1.38       0.00      
10947  0.00      0.00      0.00      0.0     5.96       1.99       1.32      
10948  0.00      1.19      0.00      0.0     5.95       1.19       2.38      

       L_discrep  L_tentat  L_certain  L_differ  L_percept  L_see  L_hear  \
10944  2.55       1.91      1.27       0.64      5.10       1.91   1.91     
10945  0.81       1.61      0.81       0.81      4.03       0.00   4.03     
10946  1.38       2.76      0.00       4.83      3.45       2.76   0

In [7]:
all_Features['urlType'].unique()

array(['Reliable', 'Fake'], dtype=object)

In [8]:
list(all_Features.columns)

['domain',
 'url',
 'urlType',
 'L_WC',
 'L_Analytic',
 'L_Clout',
 'L_Authentic',
 'L_Tone',
 'L_WPS',
 'L_Sixltr',
 'L_Dic',
 'L_function',
 'L_pronoun',
 'L_ppron',
 'L_i',
 'L_we',
 'L_you',
 'L_shehe',
 'L_they',
 'L_ipron',
 'L_article',
 'L_prep',
 'L_auxverb',
 'L_adverb',
 'L_conj',
 'L_negate',
 'L_verb',
 'L_adj',
 'L_compare',
 'L_interrog',
 'L_number',
 'L_quant',
 'L_affect',
 'L_posemo',
 'L_negemo',
 'L_anx',
 'L_anger',
 'L_sad',
 'L_social',
 'L_family',
 'L_friend',
 'L_female',
 'L_male',
 'L_cogproc',
 'L_insight',
 'L_cause',
 'L_discrep',
 'L_tentat',
 'L_certain',
 'L_differ',
 'L_percept',
 'L_see',
 'L_hear',
 'L_feel',
 'L_bio',
 'L_body',
 'L_health',
 'L_sexual',
 'L_ingest',
 'L_drives',
 'L_affiliation',
 'L_achieve',
 'L_power',
 'L_reward',
 'L_risk',
 'L_focuspast',
 'L_focuspresent',
 'L_focusfuture',
 'L_relativ',
 'L_motion',
 'L_space',
 'L_time',
 'L_work',
 'L_leisure',
 'L_home',
 'L_money',
 'L_relig',
 'L_death',
 'L_informal',
 'L_swear',
 '

In [9]:
#Slicing of data to devide it into target and feature set
X=all_Features.drop(columns=['url','domain','urlType'])
y=all_Features['urlType'].to_frame()

# Decision Tree with criterion gini index [DT(G)] Classification

In [10]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.2, random_state = 100)

In [11]:
clf_gini = DecisionTreeClassifier(criterion = "gini", random_state = 100)
clf_gini.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=100, splitter='best')

In [13]:
y_pred_gi = clf_gini.predict(X_test)
y_pred_gi

array(['Fake', 'Fake', 'Fake', ..., 'Reliable', 'Fake', 'Reliable'],
      dtype=object)

In [14]:
print(confusion_matrix(y_test, y_pred_gi))

[[939 169]
 [162 920]]


In [15]:
print("Accuracy is {}".format(accuracy_score(y_test,y_pred_gi)*100))

Accuracy is 84.88584474885845


In [16]:
del X_train, X_test, y_train, y_test

# Decision Tree with criterion entropy index [DT(E)] Classification

In [17]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.2, random_state = 100)

In [18]:
clf_entropy = DecisionTreeClassifier(criterion = "entropy", random_state = 100)
clf_entropy.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=100, splitter='best')

In [20]:
y_pred_en = clf_entropy.predict(X_test)
y_pred_en

array(['Reliable', 'Reliable', 'Fake', ..., 'Fake', 'Fake', 'Fake'],
      dtype=object)

In [21]:
print(confusion_matrix(y_test, y_pred_en))

[[938 170]
 [185 897]]


In [22]:
print("Accuracy is {}".format(accuracy_score(y_test,y_pred_en)*100))

Accuracy is 83.78995433789954


In [23]:
del X_train, X_test, y_train, y_test

# K-Nearest Neighbors (KNN) Classification

In [24]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.2, random_state = 100)

In [25]:
classifier = KNeighborsClassifier(n_neighbors=5)

In [26]:
classifier.fit(X_train, y_train)

/Users/shekharsingh/anaconda3/envs/FakeNewsEnv1/lib/python3.6/site-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [27]:
y_pred_knn = classifier.predict(X_test)

In [28]:
print(confusion_matrix(y_test, y_pred_knn))

[[829 279]
 [339 743]]


In [29]:
print ("Accuracy is {}".format(accuracy_score(y_test,y_pred_knn)*100))

Accuracy is 71.78082191780823


In [30]:
del X_train, X_test, y_train, y_test

# Random Forest (RF) Classification

In [31]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.2, random_state = 100)

In [32]:
model_tree = RandomForestClassifier(random_state=100, n_estimators=100)
model_tree.fit(X_train, y_train)

/Users/shekharsingh/anaconda3/envs/FakeNewsEnv1/lib/python3.6/site-packages/ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=100,
                       verbose=0, warm_start=False)

In [33]:
y_pred_rf = model_tree.predict(X_test)

In [34]:
print(confusion_matrix(y_test, y_pred_rf))

[[1026   82]
 [  94  988]]


In [35]:
print ("Accuracy is {}".format(accuracy_score(y_test,y_pred_rf)*100))

Accuracy is 91.9634703196347


In [36]:
del X_train, X_test, y_train, y_test

# Support Vector Machine (SVM) Classification 

In [37]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.2, random_state = 100)

In [38]:
clf = svm.SVC(kernel='linear')

In [39]:
clf.fit(X_train, y_train)

/Users/shekharsingh/anaconda3/envs/FakeNewsEnv1/lib/python3.6/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [40]:
y_pred_svm = clf.predict(X_test)

In [41]:
print(confusion_matrix(y_test, y_pred_svm))

[[1006  102]
 [ 111  971]]


In [42]:
print ("Accuracy is {}".format(accuracy_score(y_test,y_pred_svm)*100))

Accuracy is 90.27397260273973


In [43]:
del X_train, X_test, y_train, y_test

# Logistic Regression (LR) Classification

In [44]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.2, random_state = 100)

In [45]:
logisticRegr = LogisticRegression()

In [46]:
logisticRegr.fit(X_train, y_train)

/Users/shekharsingh/anaconda3/envs/FakeNewsEnv1/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/shekharsingh/anaconda3/envs/FakeNewsEnv1/lib/python3.6/site-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/shekharsingh/anaconda3/envs/FakeNewsEnv1/lib/python3.6/site-packages/sklearn/svm/base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [47]:
y_pred_lr = logisticRegr.predict(X_test)

In [48]:
print(confusion_matrix(y_test, y_pred_lr))

[[891 217]
 [225 857]]


In [49]:
print ("Accuracy is {}".format(accuracy_score(y_test,y_pred_lr)*100))

Accuracy is 79.81735159817352


In [50]:
del X_train, X_test, y_train, y_test

# XGBoost Classification

In [51]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.2, random_state = 100)

In [52]:
model = XGBClassifier(learning_rate = 0.05, n_estimators = 300, max_depth = 5)

In [53]:
model.fit(X_train, y_train)

/Users/shekharsingh/anaconda3/envs/FakeNewsEnv1/lib/python3.6/site-packages/sklearn/preprocessing/label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/shekharsingh/anaconda3/envs/FakeNewsEnv1/lib/python3.6/site-packages/sklearn/preprocessing/label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.05, max_delta_step=0, max_depth=5,
              min_child_weight=1, missing=None, n_estimators=300, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [54]:
y_pred_xg = model.predict(X_test)

In [55]:
print(confusion_matrix(y_test, y_pred_xg))

[[1049   59]
 [  74 1008]]


In [56]:
print ("Accuracy is {}".format(accuracy_score(y_test,y_pred_xg)*100))

Accuracy is 93.9269406392694


In [57]:
del X_train, X_test, y_train, y_test

# End 